// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateResume(ctx context.Context, arg CreateResumeParams) (Resume, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// ============================================
	// User Verification Link Queries
	// ============================================
	CreateVerifyLink(ctx context.Context, arg CreateVerifyLinkParams) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteRefreshToken(ctx context.Context, arg DeleteRefreshTokenParams) error
	DeleteRefreshTokenByToken(ctx context.Context, arg DeleteRefreshTokenByTokenParams) error
	DeleteResume(ctx context.Context, arg DeleteResumeParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteVerifyLink(ctx context.Context, arg DeleteVerifyLinkParams) error
	// ============================================
	// User Queries
	// ============================================
	FindUserByEmail(ctx context.Context, arg FindUserByEmailParams) (User, error)
	GetAllResumes(ctx context.Context) ([]Resume, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	// ============================================
	// Refresh Token Queries
	// ============================================
	GetRefreshTokenByToken(ctx context.Context, arg GetRefreshTokenByTokenParams) (RefreshToken, error)
	GetRefreshTokenByUserID(ctx context.Context, arg GetRefreshTokenByUserIDParams) (RefreshToken, error)
	// ============================================
	// Resume Queries
	// ============================================
	GetResume(ctx context.Context, arg GetResumeParams) (Resume, error)
	GetResumesByUserID(ctx context.Context, arg GetResumesByUserIDParams) ([]Resume, error)
	GetUser(ctx context.Context, arg GetUserParams) (User, error)
	GetVerifyLinkByToken(ctx context.Context, arg GetVerifyLinkByTokenParams) (UserVerifyLink, error)
	GetVerifyLinkByUserID(ctx context.Context, arg GetVerifyLinkByUserIDParams) (UserVerifyLink, error)
	UpdateResume(ctx context.Context, arg UpdateResumeParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	VerifyUser(ctx context.Context, arg VerifyUserParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
